### ISSUE TITLE
Function to clean extra spaces

### ISSUE THREAD

**Issue by voyeg3r** [jeffkreeftmeijer/dotfiles#1]
```
"preserve cursor position and search history
fun! CleanExtraSpaces()
    let save_cursor = getpos(".")
    let old_query = getreg('/')
    :%s/\s\+$//e
    call setpos('.', save_cursor)
    call setreg('/', old_query)
endfun
map <silent> <leader>c :call CleanExtraSpaces()<cr>
" Auto cleanup when saving
autocmd BufWritePre * :call CleanExtraSpaces() "remove espaços a mais antes de salvar
```

**Comment by jeffkreeftmeijer** [comment]
Hey Sérgio,

I've been using `autocmd BufWritePre * :%s/\s\+$//e` (https://github.com/jeffkreeftmeijer/dotfiles/blob/master/home/.vimrc#L52) get rid of trailing spaces on save and it's been working great. My Vim-fu is lacking, so why should I use yours instead? :)

**Comment by bittersweet** [comment]
Just as the comment says this preserves cursor position, the version you (and I use it as well although slightly different) use has the side-effect that your cursor jumps to the position where it last removed whitespace, so you'll have to navigate back to where you were.

Not really a big deal for me but I can see why it's annoying.

**Comment by jeffkreeftmeijer** [comment]
> > Just as the comment says this preserves cursor position.

Ouch. Noted.

I ran into this when saving a file today, so thanks for presenting a solution, Sérgio. I'll merge (something like) this in soon. :)
